name: RPG
version: '${version}'
main: org.example.code.rpg.RPG
api-version: '1.20'
load: STARTUP
commands:
  miner:
    description: Receive the Miner nth class job change book.
    usage: /miner <1st~4th class>

  money:
    description: Check your current balance.
    usage: /money

  mhelp:
    description: View the help for the MinerSurvival plugin.
    usage: /mhelp

  menu:
    description: Open the menu with various functions.
    usage: /menu

  namechange:
    description: Receive a name change token.
    usage: /namechange
